/**
 * Canonical catalog for the Role & Permission engine (API seed + CLI scripts).
 *
 * System role templates (scope: Administration — Advanced Role & Permission Engine):
 *   - Admin: full org access
 *   - Nurse: clinical / care documentation + appointments; no billing or role management
 *   - Caregiver: direct-care documentation; limited create/update; no admin audit
 *   - Billing: billing & claims; minimal clinical visibility
 *   - Read-only: auditor-friendly view-only across modules + user list + audit trail
 *
 * Admins may clone templates as-is or customize after creation.
 */

const PERMISSIONS = [
  { module: "RESIDENTS", action: "view", name: "View residents" },
  { module: "RESIDENTS", action: "create", name: "Create residents" },
  { module: "RESIDENTS", action: "update", name: "Update residents" },
  { module: "RESIDENTS", action: "delete", name: "Delete residents" },
  { module: "RESIDENTS", action: "manage_documents", name: "Manage resident documents" },
  { module: "PROGRESS_NOTES", action: "view", name: "View progress notes" },
  { module: "PROGRESS_NOTES", action: "create", name: "Create progress notes" },
  { module: "PROGRESS_NOTES", action: "update", name: "Update progress notes" },
  { module: "PROGRESS_NOTES", action: "delete", name: "Delete progress notes" },
  { module: "PROGRESS_NOTES", action: "export", name: "Export progress notes" },
  { module: "EMAR", action: "view", name: "View eMAR" },
  { module: "EMAR", action: "create", name: "Create eMAR records" },
  { module: "EMAR", action: "update", name: "Update eMAR records" },
  { module: "EMAR", action: "delete", name: "Delete eMAR records" },
  { module: "EMAR", action: "export", name: "Export eMAR" },
  { module: "BEHAVIORAL", action: "view", name: "View behavioral" },
  { module: "BEHAVIORAL", action: "create", name: "Create behavioral logs" },
  { module: "BEHAVIORAL", action: "update", name: "Update behavioral logs" },
  { module: "BEHAVIORAL", action: "delete", name: "Delete behavioral logs" },
  { module: "BEHAVIORAL", action: "export", name: "Export behavioral" },
  { module: "NCP", action: "view", name: "View NCP" },
  { module: "NCP", action: "create", name: "Create NCP extractions" },
  { module: "NCP", action: "update", name: "Update NCP extractions" },
  { module: "NCP", action: "delete", name: "Delete NCP extractions" },
  { module: "NCP", action: "download_docx", name: "Download NCP DOCX" },
  { module: "CARE_PLANS", action: "view", name: "View care plans" },
  { module: "CARE_PLANS", action: "create", name: "Create care plans" },
  { module: "CARE_PLANS", action: "update", name: "Update care plans" },
  { module: "CARE_PLANS", action: "delete", name: "Delete care plans" },
  { module: "CARE_PLANS", action: "approve", name: "Approve care plans" },
  { module: "CARE_PLANS", action: "export", name: "Export care plans" },
  { module: "BILLING", action: "view", name: "View billing" },
  { module: "BILLING", action: "create", name: "Create billing" },
  { module: "BILLING", action: "update", name: "Update billing" },
  { module: "BILLING", action: "delete", name: "Delete billing" },
  { module: "CLAIMS_BILLING", action: "view", name: "View claims billing" },
  { module: "CLAIMS_BILLING", action: "create", name: "Create claims billing" },
  { module: "CLAIMS_BILLING", action: "update", name: "Update claims billing" },
  { module: "CLAIMS_BILLING", action: "delete", name: "Delete claims billing" },
  { module: "CLAIMS_BILLING", action: "export", name: "Export claims billing" },
  { module: "CLAIMS_BILLING", action: "manage_provider", name: "Manage provider settings" },
  { module: "FACILITY", action: "view", name: "View facility" },
  { module: "FACILITY", action: "create", name: "Create facility" },
  { module: "FACILITY", action: "update", name: "Update facility" },
  { module: "FACILITY", action: "delete", name: "Delete facility" },
  { module: "FACILITY", action: "manage_documents", name: "Manage facility documents" },
  { module: "STAFF", action: "view", name: "View staff" },
  { module: "STAFF", action: "create", name: "Create staff" },
  { module: "STAFF", action: "update", name: "Update staff" },
  { module: "STAFF", action: "delete", name: "Delete staff" },
  { module: "STAFF", action: "manage_documents", name: "Manage staff documents" },
  { module: "ORGANIZATION", action: "view", name: "View organization" },
  { module: "ORGANIZATION", action: "update", name: "Update organization" },
  { module: "ADMINISTRATION", action: "view_users", name: "View users" },
  { module: "ADMINISTRATION", action: "invite_user", name: "Invite user" },
  { module: "ADMINISTRATION", action: "update_user", name: "Update user" },
  { module: "ADMINISTRATION", action: "view_audit", name: "View audit trail" },
  { module: "ADMINISTRATION", action: "manage_roles", name: "Manage roles and permissions" },
  { module: "FORMS", action: "view", name: "View forms" },
  { module: "FORMS", action: "create", name: "Create forms" },
  { module: "FORMS", action: "update", name: "Update forms" },
  { module: "FORMS", action: "delete", name: "Delete forms" },
  { module: "FORMS", action: "submit", name: "Submit forms" },
  { module: "COMPLIANCE", action: "view", name: "View compliance" },
  { module: "APPOINTMENTS", action: "view", name: "View appointments" },
  { module: "APPOINTMENTS", action: "create", name: "Create appointments" },
  { module: "APPOINTMENTS", action: "update", name: "Update appointments" },
  { module: "APPOINTMENTS", action: "delete", name: "Delete appointments" },
];

/**
 * System templates: isSystemTemplate roles with tenantId null, seeded for "use as-is" or customize.
 * permissionKeys: "ALL" (Admin) or "MODULE:action" list.
 */
const SYSTEM_ROLE_TEMPLATES = [
  {
    name: "Admin",
    description:
      "Full access to all modules and settings for the organization (template; customize if needed).",
    permissionKeys: "ALL",
  },
  {
    name: "Nurse",
    description:
      "Clinical and care documentation, including appointments; no billing or role management.",
    permissionKeys: [
      "RESIDENTS:view",
      "RESIDENTS:create",
      "RESIDENTS:update",
      "RESIDENTS:manage_documents",
      "PROGRESS_NOTES:view",
      "PROGRESS_NOTES:create",
      "PROGRESS_NOTES:update",
      "PROGRESS_NOTES:delete",
      "PROGRESS_NOTES:export",
      "EMAR:view",
      "EMAR:create",
      "EMAR:update",
      "EMAR:delete",
      "EMAR:export",
      "BEHAVIORAL:view",
      "BEHAVIORAL:create",
      "BEHAVIORAL:update",
      "BEHAVIORAL:delete",
      "BEHAVIORAL:export",
      "NCP:view",
      "NCP:create",
      "NCP:update",
      "NCP:delete",
      "NCP:download_docx",
      "CARE_PLANS:view",
      "CARE_PLANS:create",
      "CARE_PLANS:update",
      "CARE_PLANS:approve",
      "CARE_PLANS:export",
      "FACILITY:view",
      "FACILITY:manage_documents",
      "STAFF:view",
      "ORGANIZATION:view",
      "ORGANIZATION:update",
      "ADMINISTRATION:view_users",
      "ADMINISTRATION:view_audit",
      "FORMS:view",
      "FORMS:create",
      "FORMS:update",
      "FORMS:submit",
      "APPOINTMENTS:view",
      "APPOINTMENTS:create",
      "APPOINTMENTS:update",
      "APPOINTMENTS:delete",
      "COMPLIANCE:view",
    ],
  },
  {
    name: "Caregiver",
    description:
      "Direct care and day-to-day documentation; view/create in key modules; no admin or billing.",
    permissionKeys: [
      "RESIDENTS:view",
      "RESIDENTS:update",
      "RESIDENTS:manage_documents",
      "PROGRESS_NOTES:view",
      "PROGRESS_NOTES:create",
      "EMAR:view",
      "EMAR:create",
      "BEHAVIORAL:view",
      "BEHAVIORAL:create",
      "FACILITY:view",
      "STAFF:view",
      "ORGANIZATION:view",
      "FORMS:view",
      "FORMS:submit",
      "APPOINTMENTS:view",
      "APPOINTMENTS:create",
      "COMPLIANCE:view",
    ],
  },
  {
    name: "Billing",
    description:
      "Claims and billing operations; read-only visibility on residents and schedules where needed.",
    permissionKeys: [
      "RESIDENTS:view",
      "BILLING:view",
      "BILLING:create",
      "BILLING:update",
      "BILLING:delete",
      "CLAIMS_BILLING:view",
      "CLAIMS_BILLING:create",
      "CLAIMS_BILLING:update",
      "CLAIMS_BILLING:delete",
      "CLAIMS_BILLING:export",
      "CLAIMS_BILLING:manage_provider",
      "ORGANIZATION:view",
      "ADMINISTRATION:view_users",
      "ADMINISTRATION:view_audit",
      "APPOINTMENTS:view",
      "COMPLIANCE:view",
    ],
  },
  {
    name: "Read-only",
    description:
      "Auditor / read-only: view across modules, plus user list and audit trail; no edits or deletes.",
    permissionKeys: [
      "RESIDENTS:view",
      "PROGRESS_NOTES:view",
      "EMAR:view",
      "BEHAVIORAL:view",
      "NCP:view",
      "CARE_PLANS:view",
      "BILLING:view",
      "CLAIMS_BILLING:view",
      "FACILITY:view",
      "STAFF:view",
      "ORGANIZATION:view",
      "ADMINISTRATION:view_users",
      "ADMINISTRATION:view_audit",
      "FORMS:view",
      "APPOINTMENTS:view",
      "COMPLIANCE:view",
    ],
  },
];

module.exports = {
  PERMISSIONS,
  SYSTEM_ROLE_TEMPLATES,
};
