/*
  Warnings:

  - The values [DOCUMENT_COMPLIANCE_EVALUATED,DOCUMENT_COMPLIANCE_REPORT_EXPORTED] on the enum `AuditAction` will be removed. If these variants are still used in the database, this will fail.
  - You are about to drop the column `medical_providers_health_coverage_health_insurance_authorized_t` on the `residents` table. All the data in the column will be lost.
  - You are about to drop the column `medical_providers_health_coverage_health_insurance_medicaid_cli` on the `residents` table. All the data in the column will be lost.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "AuditAction_new" AS ENUM ('LOGIN_SUCCESS', 'LOGIN_FAILED', 'LOGOUT', 'TOKEN_REFRESH', 'PASSWORD_RESET_REQUEST', 'PASSWORD_RESET_SUCCESS', 'EMAIL_VERIFICATION', 'USER_CREATED', 'USER_UPDATED', 'USER_DELETED', 'USER_INVITED', 'USER_ACTIVATED', 'USER_DEACTIVATED', 'TENANT_CREATED', 'TENANT_UPDATED', 'TENANT_DELETED', 'TENANT_ACTIVATED', 'TENANT_DEACTIVATED', 'FORM_CREATED', 'FORM_UPDATED', 'FORM_DELETED', 'FORM_SUBMITTED', 'FORM_DRAFT_SAVED', 'FORM_DRAFT_DELETED', 'PDF_UPLOADED', 'PDF_GENERATED', 'PDF_DOWNLOADED', 'PDF_DELETED', 'PDF_TEMPLATE_CREATED', 'PDF_TEMPLATE_UPDATED', 'PDF_TEMPLATE_DELETED', 'EMBEDDING_CREATED', 'EMBEDDING_DELETED', 'EMBEDDING_QUERIED', 'NOTE_CREATED', 'NOTE_UPDATED', 'NOTE_DELETED', 'NOTE_EXPORTED', 'BILLING_TIER_CREATED', 'BILLING_TIER_UPDATED', 'BILLING_TIER_DELETED', 'RESIDENT_TIER_ASSIGNED', 'RESIDENT_TIER_UPDATED', 'INVOICE_GENERATED', 'INVOICE_UPDATED', 'INVOICE_STATUS_CHANGED', 'INVOICE_EXPORTED', 'MEDICATION_CREATED', 'MEDICATION_UPDATED', 'MEDICATION_DELETED', 'MEDICATION_ACTIVATED', 'MEDICATION_DEACTIVATED', 'MAR_RECORD_CREATED', 'MAR_RECORD_UPDATED', 'MAR_RECORD_DELETED', 'MAR_RECORD_LOCKED', 'MAR_RECORD_UNLOCKED', 'PRN_RECORD_CREATED', 'PRN_RECORD_UPDATED', 'PRN_RECORD_COMPLETED', 'VITALS_RECORDED', 'VITALS_UPDATED', 'MAR_EXPORTED', 'MAR_SCHEDULE_GENERATED', 'SYSTEM_ERROR', 'ACCESS_DENIED', 'UNAUTHORIZED_ACCESS', 'BEHAVIORAL_LOG_CREATED', 'BEHAVIORAL_LOG_UPDATED', 'BEHAVIORAL_LOG_DELETED', 'PHI_EXTRACT_NCP', 'PHI_UPDATE_NCP', 'PHI_GENERATE_NCP_DOCX', 'PHI_DOWNLOAD_NCP_DOCX', 'PHI_GENERATE_NCP_DSHS_DRAFT', 'BEHAVIORAL_NOTE_GENERATED', 'BEHAVIORAL_NOTE_UPDATED', 'BEHAVIORAL_REPORT_EXPORTED', 'CARE_PLAN_CREATED', 'CARE_PLAN_UPDATED', 'CARE_PLAN_ARCHIVED', 'CARE_PLAN_APPROVED', 'CARE_PLAN_PROBLEM_ADDED', 'CARE_PLAN_PROBLEM_REMOVED', 'CARE_PLAN_GOAL_ADDED', 'CARE_PLAN_GOAL_UPDATED', 'CARE_PLAN_INTERVENTION_ADDED', 'CARE_PLAN_INTERVENTION_UPDATED', 'CARE_PLAN_VERSION_CREATED', 'CARE_PLAN_EXPORTED', 'CARE_LIBRARY_CREATED', 'CARE_LIBRARY_UPDATED', 'CARE_LIBRARY_DELETED', 'APPOINTMENT_CREATED', 'APPOINTMENT_UPDATED', 'APPOINTMENT_DELETED', 'DOCUSIGN_ENVELOPE_SENT', 'DOCUSIGN_ENVELOPE_VOIDED', 'PHI_ACCESS_MEDICATIONS', 'PHI_ACCESS_MAR', 'PHI_ACCESS_PRN', 'PHI_ACCESS_VITALS', 'PHI_ACCESS_CARE_PLAN', 'PHI_ACCESS_BEHAVIORAL', 'PHI_ACCESS_NOTE', 'PHI_ACCESS_RESIDENT', 'PHI_CREATE_MEDICATION', 'PHI_CREATE_MAR_RECORD', 'PHI_CREATE_PRN_RECORD', 'PHI_CREATE_VITAL_SIGN', 'PHI_CREATE_CARE_PLAN', 'PHI_CREATE_BEHAVIORAL_LOG', 'PHI_CREATE_NOTE', 'PHI_CREATE_RESIDENT', 'PHI_UPDATE_MEDICATION', 'PHI_UPDATE_MAR_RECORD', 'PHI_UPDATE_PRN_RECORD', 'PHI_UPDATE_VITAL_SIGN', 'PHI_UPDATE_CARE_PLAN', 'PHI_UPDATE_BEHAVIORAL_LOG', 'PHI_UPDATE_NOTE', 'PHI_UPDATE_RESIDENT', 'PHI_DELETE_MEDICATION', 'PHI_DELETE_CARE_PLAN', 'PHI_DELETE_NOTE', 'PHI_DELETE_RESIDENT', 'FACILITY_PROFILE_CREATED', 'FACILITY_PROFILE_UPDATED', 'FACILITY_DOCUMENT_UPLOADED', 'FACILITY_DOCUMENT_MODIFIED', 'FACILITY_DOCUMENT_DELETED', 'FACILITY_DOCUMENT_VIEWED', 'FACILITY_FOLDER_CREATED', 'FACILITY_FOLDER_UPDATED', 'FACILITY_FOLDER_DELETED', 'EVACUATION_DRILL_CREATED', 'EVACUATION_DRILL_COMPLETED', 'VISITOR_CHECK_IN', 'VISITOR_CHECK_OUT', 'VISITOR_QR_SIGN_IN', 'STAFF_MEMBER_CREATED', 'STAFF_MEMBER_UPDATED', 'STAFF_MEMBER_DELETED', 'STAFF_FACILITY_ASSIGNED', 'STAFF_FACILITY_UNASSIGNED', 'STAFF_FOLDER_CREATED', 'STAFF_FOLDER_UPDATED', 'STAFF_FOLDER_DELETED', 'STAFF_DOCUMENT_UPLOADED', 'STAFF_DOCUMENT_MODIFIED', 'STAFF_DOCUMENT_DELETED', 'RESIDENT_FOLDER_CREATED', 'RESIDENT_FOLDER_UPDATED', 'RESIDENT_FOLDER_DELETED', 'RESIDENT_DOCUMENT_UPLOADED', 'RESIDENT_DOCUMENT_MODIFIED', 'RESIDENT_DOCUMENT_DELETED', 'RESIDENT_DOCUMENT_PINNED', 'RESIDENT_DOCUMENT_UNPINNED', 'ROLE_CREATED', 'ROLE_UPDATED', 'ROLE_DELETED', 'ROLE_PERMISSION_GRANTED', 'ROLE_PERMISSION_REVOKED', 'USER_ROLE_ASSIGNED', 'USER_ROLE_UNASSIGNED', 'BIRTHDAY_REMINDER_SENT', 'BIRTHDAY_CONFIG_UPDATED', 'INCIDENT_REPORT_CREATED', 'INCIDENT_REPORT_UPDATED', 'INCIDENT_STATUS_CHANGED', 'INCIDENT_COMPLIANCE_CHECKED');
ALTER TABLE "audit_logs" ALTER COLUMN "action" TYPE "AuditAction_new" USING ("action"::text::"AuditAction_new");
ALTER TYPE "AuditAction" RENAME TO "AuditAction_old";
ALTER TYPE "AuditAction_new" RENAME TO "AuditAction";
DROP TYPE "AuditAction_old";
COMMIT;

-- AlterTable
ALTER TABLE "residents" DROP COLUMN "medical_providers_health_coverage_health_insurance_authorized_t",
DROP COLUMN "medical_providers_health_coverage_health_insurance_medicaid_cli",
ADD COLUMN     "medical_providers_health_coverage_health_insurance_authorized_tier" BOOLEAN,
ADD COLUMN     "medical_providers_health_coverage_health_insurance_medicaid_client_id" TEXT;

-- CreateTable
CREATE TABLE "docusign_envelopes" (
    "id" TEXT NOT NULL,
    "envelope_id" TEXT NOT NULL,
    "resident_id" TEXT NOT NULL,
    "tenant_id" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'sent',
    "signer_name" TEXT NOT NULL,
    "signer_email" TEXT NOT NULL,
    "document_name" TEXT NOT NULL,
    "signed_at" TIMESTAMP(3),
    "completed_at" TIMESTAMP(3),
    "signed_document_url" TEXT,
    "signed_document_s3_key" TEXT,
    "created_by" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "deleted_at" TIMESTAMP(3),

    CONSTRAINT "docusign_envelopes_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "docusign_envelopes_envelope_id_key" ON "docusign_envelopes"("envelope_id");

-- CreateIndex
CREATE INDEX "docusign_envelopes_tenant_id_idx" ON "docusign_envelopes"("tenant_id");

-- CreateIndex
CREATE INDEX "docusign_envelopes_resident_id_idx" ON "docusign_envelopes"("resident_id");

-- CreateIndex
CREATE INDEX "docusign_envelopes_envelope_id_idx" ON "docusign_envelopes"("envelope_id");

-- CreateIndex
CREATE INDEX "docusign_envelopes_status_idx" ON "docusign_envelopes"("status");

-- CreateIndex
CREATE INDEX "docusign_envelopes_deleted_at_idx" ON "docusign_envelopes"("deleted_at");

-- RenameIndex
ALTER INDEX "document_compliance_notifications_tenantId_entityType_entityId_" RENAME TO "document_compliance_notifications_tenantId_entityType_entit_idx";
