/**
 * Universal letterhead for platform-generated PDFs (CareAIFlow).
 * Layout follows the universal CareAIFlow artwork:
 * logo tile + brand on the left, rounded contact card on the right.
 * Use prepareLetterheadAssets() once, then addLetterheadPage() for each page before drawing content.
 */

const { rgb, StandardFonts, degrees } = require("pdf-lib");
const axios = require("axios");
const sharp = require("sharp");
const prisma = require("../../lib/prisma");
const { downloadFileFromS3 } = require("../../utils/s3.util");
const { LETTERHEAD_CONTACT_ICON_SVGS } = require("./letterheadContactIconSvgs");

/** Letterhead height (points) — two-column layout; includes ~3mm top inset for breathing room */
const LETTERHEAD_HEADER_HEIGHT = 99;
/** ~3mm — shift logo/contact cluster down within the band */
const HEADER_TOP_PADDING_PT = (3 * 72) / 25.4;
const LETTERHEAD_FOOTER_HEIGHT = 38;
/** Space (pts) between bottom of header band and first content line. */
const LETTERHEAD_HEADER_BOTTOM_MARGIN = 26;
const FOOTER_DISCLAIMER = "Generated by CareAIFlow Platform.";
const MM_TO_PT = 72 / 25.4;

/** @type {number} Left/right margin for body content (pts) */
const BODY_MARGIN = 50;

/** Report letterhead — dark green facility name (#0E7515); contact icons use same fill in SVGs */
const THEME = {
  brand: rgb(14 / 255, 117 / 255, 21 / 255),
  headerBg: rgb(1, 1, 1),
  text: rgb(33 / 255, 41 / 255, 48 / 255),
  divider: rgb(233 / 255, 238 / 255, 240 / 255),
  white: rgb(1, 1, 1),
  /** Large subtle ellipse — matches browser letterhead */
  headerBubbleSoft: rgb(220 / 255, 240 / 255, 204 / 255),
};

/** SVG path for a rounded rectangle (y downward), origin top-left — pairs with pdf-lib drawSvgPath Y-flip + translate. */
function roundedRectSvgPath(width, height, rxRaw) {
  const r = Math.min(rxRaw, width / 2, height / 2);
  const w = width;
  const h = height;
  return [
    `M ${r} 0`,
    `L ${w - r} 0`,
    `Q ${w} 0 ${w} ${r}`,
    `L ${w} ${h - r}`,
    `Q ${w} ${h} ${w - r} ${h}`,
    `L ${r} ${h}`,
    `Q 0 ${h} 0 ${h - r}`,
    `L 0 ${r}`,
    `Q 0 0 ${r} 0`,
    "Z",
  ].join(" ");
}

function formatLetterheadLicenseExp(value) {
  if (!value) return null;
  try {
    const dt = value instanceof Date ? value : new Date(value);
    if (Number.isNaN(dt.getTime())) return null;
    return dt.toLocaleDateString("en-US", {
      month: "short",
      day: "numeric",
      year: "numeric",
    });
  } catch {
    return null;
  }
}

function wrapLines(text, maxWidth, font, fontSize) {
  if (!text || !String(text).trim()) return [];
  const words = String(text).split(/\s+/).filter(Boolean);
  const lines = [];
  let line = "";
  const w = (s) => font.widthOfTextAtSize(s, fontSize);
  for (const word of words) {
    const next = line ? `${line} ${word}` : word;
    if (w(next) <= maxWidth) line = next;
    else {
      if (line) lines.push(line);
      line = word;
    }
  }
  if (line) lines.push(line);
  return lines;
}

/**
 * Raster SVG silhouettes once per document; solid fill #0E7515 in source SVGs.
 * @param {import('pdf-lib').PDFDocument} pdfDoc
 */
async function embedLetterheadContactIcons(pdfDoc) {
  const PX = 64;
  /** @type {Record<string, import('pdf-lib').PDFImage | null>} */
  const out = {};
  for (const kind of ["address", "phone", "email", "website"]) {
    try {
      const pngBuf = await sharp(Buffer.from(LETTERHEAD_CONTACT_ICON_SVGS[kind], "utf8"))
        .resize(PX, PX)
        .png()
        .toBuffer();
      out[kind] = await pdfDoc.embedPng(pngBuf);
    } catch (e) {
      console.warn("[letterhead] Contact icon raster failed:", kind, e?.message || e);
      out[kind] = null;
    }
  }
  return out;
}

/** Solid PNG icons — `cy` is vertical center (PDF points). Height ~9pt matches contact line size. */
function drawContactIconImage(page, kind, iconX, cy, embeddedByKind, drawHPt = 9) {
  const img = embeddedByKind[kind];
  if (!img) return;
  const iw = img.width;
  const ih = img.height;
  const scale = drawHPt / ih;
  const drawH = drawHPt;
  const drawW = iw * scale;
  page.drawImage(img, {
    x: iconX - drawW / 2,
    y: cy - drawH / 2,
    width: drawW,
    height: drawH,
  });
}

/**
 * Load facility + optional QR branding for letterhead.
 * @param {string} tenantId
 * @param {string} [facilityId]
 * @returns {Promise<Object>}
 */
async function loadLetterheadContext(tenantId, facilityId) {
  let facility = null;
  if (facilityId) {
    facility = await prisma.facility.findFirst({
      where: { id: facilityId, tenantId },
      include: { qrConfig: true },
    });
  }
  if (!facility) {
    facility = await prisma.facility.findFirst({
      where: { tenantId },
      include: { qrConfig: true },
      orderBy: { name: "asc" },
    });
  }

  const tenant = await prisma.tenant.findUnique({ where: { id: tenantId } });

  const displayName =
    facility?.qrConfig?.facilityDisplayName?.trim() ||
    facility?.name?.trim() ||
    tenant?.name?.trim() ||
    "Facility";

  const defaultConfig = {
    showLogo: true, showAddress: true, showPhone: true,
    showEmail: true, showWebsite: true, showLicense: true,
  };
  const cfg = facility?.letterheadConfig
    ? { ...defaultConfig, ...facility.letterheadConfig }
    : defaultConfig;

  let logoBytes = null;
  if (cfg.showLogo) {
    if (facility?.profilePhotoS3Key) {
      try {
        const buf = await downloadFileFromS3(facility.profilePhotoS3Key);
        logoBytes = new Uint8Array(buf);
      } catch (e) {
        /* ignore */
      }
    }
    if (!logoBytes && facility?.profilePhotoUrl) {
      try {
        const res = await axios.get(facility.profilePhotoUrl, {
          responseType: "arraybuffer",
          timeout: 20000,
          maxRedirects: 5,
          validateStatus: (s) => s === 200,
        });
        logoBytes = new Uint8Array(res.data);
      } catch (e) {
        /* ignore */
      }
    }
    if (!logoBytes && facility?.qrConfig?.logoS3Key) {
      try {
        const buf = await downloadFileFromS3(facility.qrConfig.logoS3Key);
        logoBytes = new Uint8Array(buf);
      } catch (e) {
        /* ignore */
      }
    }
    if (!logoBytes && facility?.qrConfig?.logoUrl) {
      try {
        const res = await axios.get(facility.qrConfig.logoUrl, {
          responseType: "arraybuffer",
          timeout: 20000,
          validateStatus: (s) => s === 200,
        });
        logoBytes = new Uint8Array(res.data);
      } catch (e) {
        /* ignore */
      }
    }
  }

  return {
    displayName,
    address: cfg.showAddress ? (facility?.address || null) : null,
    phone: cfg.showPhone ? (facility?.contactInformation || null) : null,
    contactEmail: cfg.showEmail ? (facility?.contactEmail?.trim() || null) : null,
    website: cfg.showWebsite ? (facility?.website?.trim() || null) : null,
    licenseNumber: cfg.showLicense ? (facility?.licenseNumber || null) : null,
    licenseExpirationDate: cfg.showLicense ? facility?.licenseExpirationDate ?? null : null,
    tenantName: tenant?.name || null,
    logoBytes,
    showLogo: Boolean(cfg.showLogo),
  };
}

/**
 * Embed logo once for reuse on multiple pages.
 * @param {import('pdf-lib').PDFDocument} pdfDoc
 * @param {Uint8Array|null} logoBytes
 */
async function embedLogoImage(pdfDoc, logoBytes) {
  if (!logoBytes || logoBytes.length === 0) return null;
  try {
    const isPng = logoBytes[0] === 0x89 && logoBytes[1] === 0x50;
    const embedded = isPng
      ? await pdfDoc.embedPng(logoBytes)
      : await pdfDoc.embedJpg(logoBytes);
    return embedded;
  } catch (e) {
    // Non-JPEG/PNG formats (e.g. WEBP) are converted to PNG for pdf-lib.
    try {
      const convertedPng = await sharp(Buffer.from(logoBytes)).png().toBuffer();
      return await pdfDoc.embedPng(convertedPng);
    } catch (convErr) {
      console.warn("[letterhead] Could not embed logo:", convErr?.message || e?.message);
      return null;
    }
  }
}

/** Square cover crop + rounded-rect alpha so bitmap matches drawSvgPath border radius (no white gap). */
async function embedLetterheadLogoImage(pdfDoc, logoBytes) {
  if (!logoBytes || logoBytes.length === 0) return null;
  const OUT = 256;
  const rx = Math.min(Math.round(OUT * 0.12), 30);
  const maskSvg = Buffer.from(
    `<svg xmlns="http://www.w3.org/2000/svg" width="${OUT}" height="${OUT}"><rect width="${OUT}" height="${OUT}" rx="${rx}" ry="${rx}" fill="#fff"/></svg>`,
  );
  try {
    const piped = await sharp(Buffer.from(logoBytes))
      .resize(OUT, OUT, { fit: "cover", position: "center" })
      .ensureAlpha()
      .composite([{ input: maskSvg, blend: "dest-in" }])
      .png()
      .toBuffer();
    return await pdfDoc.embedPng(piped);
  } catch (e) {
    console.warn("[letterhead] Rounded logo mask failed, using plain embed:", e?.message || e);
    return embedLogoImage(pdfDoc, logoBytes);
  }
}

/**
 * @param {import('pdf-lib').PDFDocument} pdfDoc
 * @param {string} tenantId
 * @param {string} [facilityId]
 */
async function prepareLetterheadAssets(pdfDoc, tenantId, facilityId) {
  const context = await loadLetterheadContext(tenantId, facilityId);
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
  const embeddedLogo = await embedLetterheadLogoImage(pdfDoc, context.logoBytes);
  const contactIcons = await embedLetterheadContactIcons(pdfDoc);
  const pageHeight = 792;
  const contentStartY =
    pageHeight - LETTERHEAD_HEADER_HEIGHT - LETTERHEAD_HEADER_BOTTOM_MARGIN;
  return {
    context,
    fonts: { font, boldFont, semiBoldFont: font },
    embeddedLogo,
    contactIcons,
    contentStartY,
    letterheadHeaderHeight: LETTERHEAD_HEADER_HEIGHT,
    letterheadFooterHeight: LETTERHEAD_FOOTER_HEIGHT,
    bodyMargin: BODY_MARGIN,
  };
}

/**
 * Draw letterhead header + footer on an existing page (sync; logo already embedded).
 * @param {import('pdf-lib').PDFPage} page
 * @param {import('pdf-lib').PDFDocument} pdfDoc
 * @param {Object} assets - from prepareLetterheadAssets
 */
function drawLetterheadOnPage(page, pdfDoc, assets) {
  const { context, fonts, contactIcons } = assets;
  const { font, boldFont } = fonts;
  const { width, height } = page.getSize();
  const headerBottom = height - LETTERHEAD_HEADER_HEIGHT;
  const innerCenterY =
    headerBottom +
    LETTERHEAD_HEADER_HEIGHT / 2 -
    HEADER_TOP_PADDING_PT / 2;
  const inset = BODY_MARGIN;

  // Header background
  page.drawRectangle({
    x: 0, y: headerBottom,
    width, height: LETTERHEAD_HEADER_HEIGHT,
    color: THEME.headerBg,
  });

  const BUBBLE_SHIFT_LEFT_PT = (100 * 72) / 96;
  const BUBBLE_SHIFT_DOWN_PT = (34 * 72) / 96;
  const bubbleSizeBase = Math.min(52, width * 0.078);
  const bubbleRx = bubbleSizeBase * 1.15 * 1.1;
  const bubbleRy = bubbleRx * 1.12;
  const bubbleCx = width - inset - bubbleRx * 0.22 - BUBBLE_SHIFT_LEFT_PT;
  const bubbleCy = headerBottom + bubbleRy * 0.72 - BUBBLE_SHIFT_DOWN_PT;
  page.drawEllipse({
    x: bubbleCx,
    y: bubbleCy,
    xScale: bubbleRx,
    yScale: bubbleRy,
    rotate: degrees(-10),
    color: THEME.headerBubbleSoft,
    borderWidth: 0,
    opacity: 0.5,
  });

  // Bottom divider — full page width under the letterhead band
  page.drawRectangle({
    x: 0,
    y: headerBottom,
    width,
    height: 0.8,
    color: THEME.divider,
  });

  // Left: logo tile
  const LOGO_SIZE = 50;
  const logoX = inset;
  const logoY = innerCenterY - LOGO_SIZE / 2;
  const showLogo = context.showLogo !== false;
  const hasLogo = Boolean(assets.embeddedLogo);

  if (showLogo && hasLogo) {
    try {
      const img = assets.embeddedLogo;
      page.drawImage(img, {
        x: logoX,
        y: logoY,
        width: LOGO_SIZE,
        height: LOGO_SIZE,
      });
      const logoRx = Math.min(6, LOGO_SIZE * 0.12);
      page.drawSvgPath(roundedRectSvgPath(LOGO_SIZE, LOGO_SIZE, logoRx), {
        x: logoX,
        y: logoY + LOGO_SIZE,
        borderColor: THEME.brand,
        borderWidth: 1.5,
      });
    } catch (_) { /* ignore */ }
  }

  // Left: brand text
  const textStartX = showLogo ? logoX + LOGO_SIZE + 10 : logoX;
  const title = (context.displayName || "CareAIFlow").substring(0, 45);
  const titleSize = 15.5;
  const licenseExpStr = formatLetterheadLicenseExp(context.licenseExpirationDate);

  if (licenseExpStr) {
    page.drawText(title, {
      x: textStartX,
      y: innerCenterY + 11,
      size: titleSize,
      font: boldFont,
      color: THEME.brand,
    });
    page.drawText(`License expires: ${licenseExpStr}`, {
      x: textStartX,
      y: innerCenterY - 4,
      size: 9,
      font,
      color: THEME.text,
    });
  } else {
    page.drawText(title, {
      x: textStartX,
      y: innerCenterY + 6,
      size: titleSize,
      font: boldFont,
      color: THEME.brand,
    });
  }

  const innerW = width - inset * 2;
  const cardW = Math.min(Math.max(170, width * 0.34), Math.max(120, innerW * 0.5));
  const cardX = width - inset - cardW;
  const rightSize = 9.2;
  const rightStep = 17;

  const rightLines = [];
  if (context.address) {
    const wrapped = wrapLines(context.address, cardW - 48, font, rightSize);
    if (wrapped[0]) rightLines.push({ text: wrapped[0], kind: "address" });
  }
  if (context.phone) rightLines.push({ text: context.phone.trim(), kind: "phone" });
  if (context.contactEmail) rightLines.push({ text: context.contactEmail.trim(), kind: "email" });
  if (context.website) {
    rightLines.push({ text: context.website.trim().replace(/^https?:\/\//i, ""), kind: "website" });
  }

  if (rightLines.length > 0) {
    const n = rightLines.length;
    const blockH = (n - 1) * rightStep;
    /** Vertically center baseline cluster in header band (pdf-lib y grows upward). */
    let ry = innerCenterY + blockH / 2;
    const iconX = cardX + cardW - 12;
    const textRightX = iconX - 16;
    for (let i = 0; i < rightLines.length; i += 1) {
      const line = rightLines[i];
      const txt = line.text.substring(0, 120);
      page.drawText(txt, {
        x: textRightX - font.widthOfTextAtSize(txt, rightSize),
        y: ry,
        size: rightSize,
        font: boldFont,
        color: THEME.text,
      });
      const rowCenterY = ry + rightSize * 0.38;
      drawContactIconImage(page, line.kind, iconX, rowCenterY, contactIcons || {});
      ry -= rightStep;
    }
  }

  // ─── Footer ───────────────────────────────────────────────────────
  // Subtle separator line above footer text
  page.drawRectangle({
    x: BODY_MARGIN, y: LETTERHEAD_FOOTER_HEIGHT + 22,
    width: width - BODY_MARGIN * 2, height: 0.4,
    color: THEME.divider,
  });
  const fw = font.widthOfTextAtSize(FOOTER_DISCLAIMER, 8);
  page.drawText(FOOTER_DISCLAIMER, {
    x: (width - fw) / 2, y: 14,
    size: 8, font,
    color: rgb(0.42, 0.44, 0.43),
  });
}

/**
 * Add a US Letter page with letterhead; return page and standard content start Y.
 * @param {import('pdf-lib').PDFDocument} pdfDoc
 * @param {Object} assets
 */
function addLetterheadPage(pdfDoc, assets) {
  const page = pdfDoc.addPage([612, 792]);
  drawLetterheadOnPage(page, pdfDoc, assets);
  return page;
}

/**
 * Minimum Y (pdf-lib, from bottom) content should not go below (leave room for footer + body).
 */
function contentBottomMin(assets) {
  return LETTERHEAD_FOOTER_HEIGHT + 45;
}

/**
 * Stamp page numbers on every page (after content), right side above footer band.
 * @param {import('pdf-lib').PDFDocument} pdfDoc
 * @param {import('pdf-lib').PDFFont} font
 * @param {number} margin
 */
function stampPageNumbers(pdfDoc, font, margin = 50) {
  const pages = pdfDoc.getPages();
  const total = pages.length;
  pages.forEach((page, index) => {
    const { width } = page.getSize();
    const label = `Page ${index + 1} of ${total}`;
    const size = 8;
    const tw = font.widthOfTextAtSize(label, size);
    page.drawText(label, {
      x: width - margin - tw,
      y: LETTERHEAD_FOOTER_HEIGHT + 6,
      size,
      font,
      color: rgb(0.45, 0.45, 0.45),
    });
  });
}

module.exports = {
  LETTERHEAD_HEADER_HEIGHT,
  LETTERHEAD_FOOTER_HEIGHT,
  FOOTER_DISCLAIMER,
  BODY_MARGIN,
  loadLetterheadContext,
  prepareLetterheadAssets,
  addLetterheadPage,
  drawLetterheadOnPage,
  embedLogoImage,
  contentBottomMin,
  stampPageNumbers,
};
